services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ../infra/redis/redis.conf:/usr/local/etc/redis/redis.conf.template
    environment:
      - REDIS_ADDR=redis:6379
    env_file: ../.env
    networks:
      - default
    command: sh -c "sed 's/{{REDIS_PASSWORD}}/${REDIS_PASSWORD}/' /usr/local/etc/redis/redis.conf.template > /usr/local/etc/redis/redis.conf && redis-server /usr/local/etc/redis/redis.conf"
    restart: always

  geshtalt:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: geshtalt
    environment:
      - REDIS_ADDR=redis:6379
    env_file: ../.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - default
    restart: always

  alice:
    build:
      context: ..
      dockerfile: docker/Dockerfile.python
    container_name: alice
    env_file:
      - ../.env
    ports:
      - "2112:2112"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - redis
      - geshtalt
    networks:
      - default
    restart: always

  telegram-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    depends_on:
      - redis
      - geshtalt
    env_file: ../.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      - default
    restart: always

  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot
      - html_www:/var/www/html
    depends_on:
      - geshtalt
      - alice
    restart: always
    networks:
      - default

volumes:
  redis_data:
  certbot_www:
  html_www:

networks:
  default:
    name: gestalt_network
