{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "gestalt.fullname" . }}-default-headers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gestalt.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
      X-Forwarded-Host: "{{ .Values.domain.name | default "localhost" }}"
{{- end }}

