apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gestalt.fullname" . }}-secrets
  labels:
    {{- include "gestalt.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | default "" | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | default "" | quote }}
  YANDEX_CLIENT_ID: {{ .Values.secrets.yandexClientId | default "" | quote }}
  YANDEX_CLIENT_SECRET: {{ .Values.secrets.yandexClientSecret | default "" | quote }}
  TELEGRAM_TOKEN: {{ .Values.secrets.telegramToken | default "" | quote }}
  SERVICE_USER_ID: {{ .Values.secrets.serviceUserId | default "" | quote }}

